Remove edamame monitoring
jenkins-infra/datadog pull request #20
Opened 2020-11-10 22:59 UTC by MarkEWaite

Do not monitor edamame, it is no longer hosting Jira

Also corrects a few URL's to use the new URL to Jira.

2020-11-10 23:00 UTC, markyjackson-taulia approved these changes

2020-11-12 13:21 UTC, olblak requested changes
IMHO we should still monitor Jira. It's a critical service for the project and it would be useful to detect if something goes wrong. I think the only interesting from this pull request is updating from issues.jenkins-ci.org links to issues.jenkins.io

2020-11-12 14:19 UTC, MarkEWaite commented
> IMHO we should still monitor Jira. It's a critical service for the project and it would be useful to detect if something goes wrong. I think the only interesting from this pull request is updating from issues.jenkins-ci.org links to issues.jenkins.io

I agree that we should still monitor Jira.  I assumed that the check `query = "\"process.up\".over(\"host:edamame\",\"process:jira\").last(6).count_by_status()"` line was referring to information datadog receives about processes that are executing on the edamame host.  I was trying to remove the monitoring that depends on a datadog agent installed on the edamame host.

I thought that host level monitoring of the computer providing the Jira service is the responsibility of the Linux Foundation just as host level monitoring of Artifactory is done by JFrog and host level monitoring of GitHub is done by GitHub.  We continue to monitor HTTP level responses from Jira.

I assume that we'll repurpose edamame to some other use for the Jenkins project and will enable monitoring of that new use when it begins.

2020-11-12 15:13 UTC, olblak approved these changes
I read this PR too quickly :)

2020-11-17 09:51 UTC, olblak approved these changes

2020-11-17 09:51 UTC, merged